# Generated by Django 5.0.6 on 2024-05-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='professions',
            field=models.ManyToManyField(related_name='tags', to='main.profession'),
        ),
    ]
