# Generated by Django 5.0.6 on 2024-05-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_professions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('Tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profession')),
            ],
            options={
                'db_table': 'interview',
            },
        ),
    ]
