# Generated by Django 5.0.6 on 2024-05-29 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='Tag',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('number_of_mentions', models.PositiveIntegerField()),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profession')),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='tag',
            field=models.ForeignKey(default='Нет', on_delete=django.db.models.deletion.CASCADE, to='main.tag'),
        ),
    ]
