# Generated by Django 5.0.6 on 2024-05-29 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_interview_tag_skill_interview_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.tag'),
        ),
    ]
